include: package:effective_dart/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    use_setters_to_change_properties: false
    avoid_catches_without_on_clauses: false
    avoid_types_on_closure_parameters: false